apiVersion: v1
kind: Service
metadata:
  name: my-service-for-nginx-deployment
spec:
  type: ClusterIP 
  selector:
    app: my-nginx-deployment-frontend # Same as deployment label
  ports:
    - port: 8080
      targetPort: 80
