apiVersion: v1
kind: Pod
metadata:
  name: "config-map-app-pod-using-filesystem"
spec:
  volumes:
    - name: app-config-volume
      configMap:
        name: garabola-app-settings
  containers:
    - name: alpine-linux-container
      volumeMounts:
        - name: app-config-volume
          mountPath: /etc/config
      image: python:alpine3.16
      command: ["/bin/sh"]
      args: [
          "-c",
          "pip install https://github.com/joh/when-changed/archive/master.zip; \
          echo \"\n\n\n\n\nInitial [$(date)]:\"; \
          cat /etc/config/garabolaName; \
          when-changed /etc/config/garabolaName -c 'echo \n>$(date); cat /etc/config/garabolaName' \
          ",
        ]
